name: web-deploy-to-ftp-staging

on:
  pull_request:
    branches: [ 'staging' ]

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
          # Here is the deployment action
      - name: Upload from public_html via FTP
        run: |
          echo "================="
          echo "Updating packages"
          echo "================="
          sudo apt-get -y update
          echo "================="
          echo "Installing lftp"
          echo "================="
          sudo apt-get -y install lftp
          echo "================="
          echo "Executing sftp"
          echo "================="
          lftp -e "set sftp:auto-confirm yes; open sftp://${{secrets.FTP_STAGING_USERNAME}}:${{secrets.FTP_STAGING_PASSWORD}}@${{secrets.FTP_STAGING_SERVER}}; mirror -R --delete --verbose --parallel=3 --ignore-time --use-pget-n=3 ./ ${{secrets.FTP_STAGING_REMOTE_FOLDER}}; bye"
          echo "================="
          echo "Finished upload"
          echo "================="