name: web-deploy-to-ftp-staging

on:
  pull_request:
    branches: [ 'staging' ]

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
          # Here is the deployment action
      - name: Upload from public_html via FTP
        run: |
          sudo apt-get -y update
          echo "installing lftp"
          sudo apt-get -y install lftp
          echo "executing sftp"
          lftp sftp://${{secrets.FTP_STAGING_USERNAME}}:${{secrets.FTP_STAGING_PASSWORD}}@${{secrets.FTP_STAGING_SERVER}} -e set net:max-retries 10 mirror --continue --reverse './' ${{secrets.FTP_STAGING_REMOTE_FOLDER}}
