name: web-deploy-to-ftp

on:
  pull_request:
    branches: [ 'master' ]

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Fast FTP Action
        uses: anvil-solutions/Fast-FTP-Action@2.1.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          remote_dir: ${{ secrets.FTP_REMOTE_FOLDER }}
          local_dir: ./
          method: sftp
