name: web-deploy-to-ftp

on:
  push:
    branches: [ 'main' ]

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fast FTP Action
        uses: anvil-solutions/Fast-FTP-Action@2.1.3
        with:
          server: ${{ secrets.FTP_PRODUCTION_SERVER }}
          username: ${{ secrets.FTP_PRODUCTION_USERNAME }}
          password: ${{ secrets.FTP_PRODUCTION_PASSWORD }}
          remote_dir: ${{secrets.FTP_PRODUCTION_REMOTE_FOLDER}}
          local_dir: '.'