name: web-deploy-to-ftp

on:
  push:
    branches: [ 'main' ]

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install lftp
        run:  sudo apt-get -y update && sudo apt-get install -y lftp
      - name: Upload via SFTP
        env:
          FTP_HOST: ${{ secrets.FTP_PRODUCTION_SERVER }}
          FTP_USER: ${{ secrets.FTP_PRODUCTION_USERNAME }}
          FTP_PASS: ${{ secrets.FTP_PRODUCTION_PASSWORD }}
          FTP_DIR: ${{secrets.FTP_PRODUCTION_REMOTE_FOLDER}}
        run: |
          echo "================="
          echo "Executing sftp"
          echo "================="
          lftp -e "set sftp:auto-confirm yes; \
                 open sftp://$FTP_USER:$FTP_PASS@$FTP_HOST; \
                 mirror -R --delete --verbose \
                 --exclude .git/ --exclude .github/ \
                 ./ $FTP_DIR; \
                 bye"
          echo "================="
          echo "Finished upload"
          echo "================="