name: web-deploy-to-ftp-staging

on:
  pull_request:
    branches: [ 'staging' ]

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fast FTP Action
        uses: anvil-solutions/Fast-FTP-Action@2.1.3
        with:
          server: ${{ secrets.FTP_STAGING_SERVER }}
          username: ${{ secrets.FTP_STAGING_USERNAME }}
          password: ${{ secrets.FTP_STAGING_PASSWORD }}
          remote_dir: ${{secrets.FTP_STAGING_REMOTE_FOLDER}}
          local_dir: '.'